---
title: Kredenc
timezone: Europe/Budapest
collections:
  authors:
    title: Authors
    output: true
    permalink: "/authors/:path/"
  comics:
    title: Comics
    output: true
    permalink: "/comics/:path/"
  creations:
    title: Creations
    output: true
  memes:
    title: Memes
    output: true
    permalink: "/memes/:path/"
  photos:
    title: Photos
    output: true
    permalink: "/photos/:path/"
  pages:
    title: Pages
    output: true
    permalink: "/pages/:title/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: memes
  values:
    show: memes
    layout: pic
- scope:
    path: ''
    type: photos
  values:
    show: photos
    layout: pic
- scope:
    path: ''
    type: comics
  values:
    show: comics
    layout: pic
- scope:
    path: ''
    type: authors
  values:
    layout: default
    type: author
author: Sarius
description: A Hajnóczy Kollégium diákmagazinja.
baseurl: "/kredenc"
url: https://dynamic0de.github.io/
social:
  name: Kredenc
  links:
  - https://github.com/Cloud4est
tagline: A Hajnóczy Kollégium újságja.
hero_img: posts/sleek_lg.jpg
email: nestgrouphu@gmail.com
disqus:
  shortname: kredenc
service_worker: true
markdown: kramdown
highlighter: rouge
exclude:
- README.md
- node_modules
- script
- package.json
- package-lock.json
- Gemfile
- Gemfile.lock
- vendor
- npm-debug.log
- gulpfile.js
- sleek.jpg
include:
- _pages
permalink: "/:title/"
compress_html:
  clippings: all
plugins:
- jekyll-sitemap
- jekyll-seo-tag
