---
title: Kredenc
timezone: Europe/Budapest
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: Sarius
description: 'A Hajnóczy Kollégium diákmagazinja.

'
baseurl: "/kredenc"
url: https://dynamic0de.github.io/
social:
  name: Kredenc
  links:
  - https://github.com/Cloud4est
navigation:
- name: Home
  link: "/"
- name: About
  link: "/about"
- name: Contact
  link: "/contact"
tagline: 'A Hajnóczy Kollégium újságja.

'
hero_img: posts/sleek_lg.jpg
email: nestgrouphu@gmail.com
disqus:
  shortname: janczizikow
service_worker: true
markdown: kramdown
highlighter: rouge
exclude:
- README.md
- node_modules
- script
- package.json
- package-lock.json
- Gemfile
- Gemfile.lock
- vendor
- npm-debug.log
- gulpfile.js
- sleek.jpg
include:
- _pages
permalink: "/:title/"
compress_html:
  clippings: all
plugins:
- jekyll-sitemap
- jekyll-seo-tag
